# Generated by Django 2.0 on 2020-08-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[('team1', 'Team 1'), ('team2', 'Team 2'), ('draw', 'Draw')], db_column='cr_match_winner', max_length=100, null=True)),
            ],
            options={
                'db_table': 'cr_match_tbl',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(db_column='cr_player_slug', max_length=255, null=True, unique=True)),
                ('firstname', models.CharField(db_column='cr_player_firstname', max_length=255)),
                ('lastname', models.CharField(db_column='cr_player_lastname', max_length=255)),
                ('image_uri', models.CharField(db_column='cr_player_image_uri', max_length=255, null=True)),
                ('jersey_number', models.CharField(db_column='cr_player_jersey_number', max_length=255)),
                ('country', models.CharField(db_column='cr_team_club_state', max_length=255)),
            ],
            options={
                'db_table': 'cr_player_tbl',
            },
        ),
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.CharField(db_column='cr_player_matches', max_length=255)),
                ('run', models.CharField(db_column='cr_player_run', max_length=255)),
                ('highest_scores', models.CharField(db_column='cr_player_highest_scores', max_length=255)),
                ('fifties', models.CharField(db_column='cr_player_fifties', max_length=255)),
                ('hundreds', models.CharField(db_column='cr_player_hundreds', max_length=255)),
            ],
            options={
                'db_table': 'cr_player_history_tbl',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(db_column='cr_team_slug', max_length=255, null=True, unique=True)),
                ('name', models.CharField(db_column='cr_team_name', max_length=255, unique=True)),
                ('logo_uri', models.CharField(db_column='cr_team_logo_uri', max_length=255, null=True)),
                ('club_state', models.CharField(db_column='cr_team_club_state', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cr_team_tbl',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='player_history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cricket.PlayerHistory'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(db_column='cr_match_team1', on_delete=django.db.models.deletion.CASCADE, related_name='match_team1', to='cricket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(db_column='cr_match_team2', on_delete=django.db.models.deletion.CASCADE, related_name='match_team2', to='cricket.Team'),
        ),
    ]
