# Generated by Django 2.0 on 2020-08-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(db_column='cr_player_team', default=1, on_delete=django.db.models.deletion.CASCADE, to='cricket.Team'),
            preserve_default=False,
        ),
    ]
