# Generated by Django 2.0 on 2020-08-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='schedule_date',
            field=models.DateTimeField(db_column='CG_URM_MODIFICATION_DT', null=True),
        ),
    ]
