# Generated by Django 2.0 on 2020-08-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_match_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('Draw', 'Draw'), ('Cancelled', 'Cancelled')], db_column='cr_match_status', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(db_column='cr_match_winner', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cr_match_winner', to='cricket.Team'),
            preserve_default=False,
        ),
    ]
